# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='null', upload_to='/'),
        ),
    ]
