# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_logo',
            field=models.FileField(default='null', upload_to='/'),
        ),
    ]
