# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_song_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_logo',
            field=models.ImageField(blank=True, null=True, upload_to='/'),
        ),
    ]
