# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20161103_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_logo',
            field=models.FileField(default='null', upload_to='/'),
        ),
    ]
