# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20161109_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_singer',
        ),
    ]
